# This file was generated by GoReleaser. DO NOT EDIT.
cask "kue" do
  version "2.0.2"

  on_macos do
    on_arm do
      sha256 "316a1c2892451c871e08493e85a1c56ceb1d7aa078a118edc3515f88333e1a9f"
      url "https://github.com/kontrolplane/kue/releases/download/v#{version}/kue_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c1db48cf22fc58e08fa86c33376b836ccf9ec7ed5458c7e6511249dc2668a411"
      url "https://github.com/kontrolplane/kue/releases/download/v#{version}/kue_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "058010f72f61274d4dc1620ca2ed664c794cfe51f17e81e5fcb2e82f6dbc7ad3"
      url "https://github.com/kontrolplane/kue/releases/download/v#{version}/kue_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cdc5160165ac1e18d7cedff65feb73ad5ddab70e69fded21c9eef0316e459523"
      url "https://github.com/kontrolplane/kue/releases/download/v#{version}/kue_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kue"
  desc "A terminal user interface (TUI) for working with Amazon Web Services Simple Queue Service."
  homepage "https://kontrolplane.dev/projects/#kue"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kue"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kue"]
    end
  end

  # No zap stanza required
end
