# This file was generated by GoReleaser. DO NOT EDIT.
cask "kue" do
  version "2.0.1"

  on_macos do
    on_arm do
      sha256 "0d74558d6b13c7f708b2413a17bba4c94cd20043c6968c1e737c104fe8fe4cd2"
      url "https://github.com/kontrolplane/kue/releases/download/v#{version}/kue_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0f200fc0d6e435cbc533f93ebe5b0a7c793914ddd53ec17eca2bdbc0a6cb6452"
      url "https://github.com/kontrolplane/kue/releases/download/v#{version}/kue_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bda4bcee3c4aadd65605cc48943a50b304998b52319a3d318ef885618860ce4b"
      url "https://github.com/kontrolplane/kue/releases/download/v#{version}/kue_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "62476d616d874a6991fceb9beeae8ba99bc82279151c0aefe356c45e774b38e3"
      url "https://github.com/kontrolplane/kue/releases/download/v#{version}/kue_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kue"
  desc "A terminal user interface (TUI) for working with Amazon Web Services Simple Queue Service."
  homepage "https://kontrolplane.dev/projects/#kue"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kue"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kue"]
    end
  end

  # No zap stanza required
end
