# This file was generated by GoReleaser. DO NOT EDIT.
cask "kue" do
  version "2.1.0"

  on_macos do
    on_arm do
      sha256 "7152789d5358317293f9094cd1a4cf57976bc1f89d881069c4b933d9e11023ed"
      url "https://github.com/kontrolplane/kue/releases/download/v#{version}/kue_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "af94be42303a08d34494cbbef061276265487fc0521016519cc4e5460317c223"
      url "https://github.com/kontrolplane/kue/releases/download/v#{version}/kue_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6c5f6f2580a89359e8274461424b9843872a5dd67713771fc5a6b8f568d01ffd"
      url "https://github.com/kontrolplane/kue/releases/download/v#{version}/kue_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9b7b73ddbbe910b498453997ee5ba0fc6935a51c7698775891c5ae6e0a9df3bc"
      url "https://github.com/kontrolplane/kue/releases/download/v#{version}/kue_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kue"
  desc "A terminal user interface (TUI) for working with Amazon Web Services Simple Queue Service."
  homepage "https://kontrolplane.dev/projects/#kue"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kue"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kue"]
    end
  end

  # No zap stanza required
end
