# This file was generated by GoReleaser. DO NOT EDIT.
cask "lekture" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "dd3df6cd2a7bc64bff7db571b87aa36211750b4840768ae87991c683d4264fb1"
      url "https://github.com/kontrolplane/lekture/releases/download/v#{version}/lekture_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "124d95b5145bd7f8ff67467956e84b94952446232e4de08aca8ecbca7fb997d5"
      url "https://github.com/kontrolplane/lekture/releases/download/v#{version}/lekture_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4e8eed30609fc29d10c1a1f02db9fd83364c8986f1038d617bd988f5f01c1afd"
      url "https://github.com/kontrolplane/lekture/releases/download/v#{version}/lekture_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e9f9501c4ef4ac28b6b16f500e0dbb0d7e858a061d24c6d1cd859d7ec37d7b9d"
      url "https://github.com/kontrolplane/lekture/releases/download/v#{version}/lekture_#{version}_linux_amd64.tar.gz"
    end
  end

  name "lekture"
  desc "A terminal user interface (TUI) for presenting markdown slideshows."
  homepage "https://kontrolplane.dev/projects/#lekture"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lekture"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lekture"]
    end
  end

  # No zap stanza required
end
