# This file was generated by GoReleaser. DO NOT EDIT.
cask "stdout" do
  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "3126be38b5b8847e2ae9d1375b715f3789e0ee0c092c7e5f3b804aa56554a03c"
      url "https://github.com/kontrolplane/stdout/releases/download/v#{version}/stdout_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "91197cdfd80a77c3245580714618299629cc34ae9bd9fe9b2bf598f6ea2a15d8"
      url "https://github.com/kontrolplane/stdout/releases/download/v#{version}/stdout_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c7202918adf4ddc91c81c4b8b31248f1aeaf1b7f1bda35d607281d3d9cd42c0b"
      url "https://github.com/kontrolplane/stdout/releases/download/v#{version}/stdout_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "aaa192497dfe645f1b26233096612a37f2cff3fbd6527b99f1a7f94d6ec9453d"
      url "https://github.com/kontrolplane/stdout/releases/download/v#{version}/stdout_#{version}_linux_amd64.tar.gz"
    end
  end

  name "stdout"
  desc "A terminal user interface for following Loki logs."
  homepage "https://kontrolplane.dev/projects/#stdout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stdout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stdout"]
    end
  end

  # No zap stanza required
end
