# This file was generated by GoReleaser. DO NOT EDIT.
cask "stdout" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "922e7ee32358c469819acc3a4b1041faf059f200b05d0cd82e8863f576b32f4c"
      url "https://github.com/kontrolplane/stdout/releases/download/v#{version}/stdout_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "dc413eab0e9d87e23ea5924af17dd598dbaa97398207790aed57cf18d23e89b9"
      url "https://github.com/kontrolplane/stdout/releases/download/v#{version}/stdout_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "02273677e6e39fe62467b133f0fadbb8be35c2c1817931a48704d83d28a68dcb"
      url "https://github.com/kontrolplane/stdout/releases/download/v#{version}/stdout_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "197e4ddba878ba2aad03caa274c28f196e517f2676f7e36ad7b8423c131334ab"
      url "https://github.com/kontrolplane/stdout/releases/download/v#{version}/stdout_#{version}_linux_amd64.tar.gz"
    end
  end

  name "stdout"
  desc "A terminal user interface for following Loki logs."
  homepage "https://kontrolplane.dev/projects/#stdout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stdout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stdout"]
    end
  end

  # No zap stanza required
end
