# This file was generated by GoReleaser. DO NOT EDIT.
cask "tsui" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "6285cad813db3d928037ed6013d05aee3ae30d3894baa02e1c6b3cc1c7bc366f"
      url "https://github.com/kontrolplane/tsui/releases/download/v#{version}/tsui_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "76b3746b7b8d660fe4664ad77104f63476f1bf84bfa727c90cd5dd6f6ff9c6ec"
      url "https://github.com/kontrolplane/tsui/releases/download/v#{version}/tsui_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "959c545e5b5ce14f45f2da6802194d777f18fc465d8c1ed38093cd868cbdf63e"
      url "https://github.com/kontrolplane/tsui/releases/download/v#{version}/tsui_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e5cfd0f8d6bddea82fba79aa6301d32e7cb6931a0d11277609d6848a688b5f84"
      url "https://github.com/kontrolplane/tsui/releases/download/v#{version}/tsui_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tsui"
  desc "A terminal user interface for NATS."
  homepage "https://kontrolplane.dev/projects/#tsui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tsui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tsui"]
    end
  end

  # No zap stanza required
end
