# This file was generated by GoReleaser. DO NOT EDIT.
cask "tsui" do
  version "1.0.2"

  on_macos do
    on_arm do
      sha256 "e87cc760c8a1427e5b2334d755c29d1cb14da69304b103b0fb1a338f905d51cf"
      url "https://github.com/kontrolplane/tsui/releases/download/v#{version}/tsui_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ed41b86c9cc4aeb311fd820fcfd0d7f0680eef6d8214aca86c052df7033f76a9"
      url "https://github.com/kontrolplane/tsui/releases/download/v#{version}/tsui_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e71eb20a61391c0319baf680e5e6717ea446340330035d99add25f39a0f15397"
      url "https://github.com/kontrolplane/tsui/releases/download/v#{version}/tsui_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5db08704f99013a1ff9ef4f2394a28ec0d8d7954b7c727b4f3494cb7b026d787"
      url "https://github.com/kontrolplane/tsui/releases/download/v#{version}/tsui_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tsui"
  desc "A terminal user interface for NATS."
  homepage "https://kontrolplane.dev/projects/#tsui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tsui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tsui"]
    end
  end

  # No zap stanza required
end
