# This file was generated by GoReleaser. DO NOT EDIT.
cask "tsui" do
  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "2e41748f895f61baa541204b72ab3ef0767fcfd24d7845dbf76217a339587971"
      url "https://github.com/kontrolplane/tsui/releases/download/v#{version}/tsui_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cb9f7d4a818ba5785a1109e3f3b34eb6d2c98ceb7e8b5fd51c5cdde99ba247fa"
      url "https://github.com/kontrolplane/tsui/releases/download/v#{version}/tsui_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "666edbc93810633b36cfe98cd816b8270db78aaddf5b292fabd5f24bdb93a181"
      url "https://github.com/kontrolplane/tsui/releases/download/v#{version}/tsui_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bc2b55974ab5f48f8922f3f2cdc09490e8a97c1c6f459a6f5865439e70c2fe8d"
      url "https://github.com/kontrolplane/tsui/releases/download/v#{version}/tsui_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tsui"
  desc "A terminal user interface for NATS."
  homepage "https://kontrolplane.dev/projects/#tsui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tsui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tsui"]
    end
  end

  # No zap stanza required
end
